

variables:
 -group: Database_variables

trigger:
- master


stages:
- stage: Build
  displayName: 'Build stage CI'
  jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          name: 'Ops-pipeline'
        steps:
           - task: CmdLine@2
             displayName: 'Delay for 10 seconds'
             inputs:
              script: 'sleep 10'

           - task: CmdLine@2
             displayName: 'Echo Variables'
             inputs:
              script: |
                  echo "DBusername:" $(DBusername)
                  echo "password:" $(password)



- stage: DEVRelease
  displayName: 'DEV Release CD'
  dependsOn: Build
  jobs:
      - deployment: DEVDeployment
        displayName: 'DEV Deployment Job'
        pool:
          name: 'Ops-pipeline'
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to DEV environment..."
                    sudo cp -R home/ubuntu/myagent/_work/2/s/* /var/www/site01/dev
                    echo "DBusername:" $(DBusername)
                    echo "password:" $(password)



- stage: PREPRODRelease
  displayName: 'PREPROD Release CD'
  dependsOn: DEVRelease
  jobs:
      - deployment: PREPRODDeployment
        displayName: 'PREPROD Deployment Job'
        environment: 'PREPROD'
        pool:
          name: 'Ops-pipeline'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to PREPROD environment..."
                    sudo cp -R home/ubuntu/myagent/_work/2/s/* /var/www/site01/preprod

- stage: PRODRelease
  displayName: 'PROD Release CD'
  dependsOn: PREPRODRelease
  jobs:
      - deployment: PRODDeployment
        displayName: 'PROD Deployment Job'
        pool:
          name: 'Ops-pipeline'
        environment: 'PROD'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to PROD environment..."
                    sudo cp -R home/ubuntu/myagent/_work/2/s/* /var/www/site01/prod

  