trigger:
- master


stages:
- stage: Build
  displayName: 'Build stage CI'
  jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          name: Ops-Pipeline
        steps:
           - task: CmdLine@2
             displayName: 'Builds'
             inputs:
              script: |
                  sudo cp -R /home/ubuntu/myagent/_work/5/s/* /var/www/practice
                  cd /var/www/practice
                  sudo docker ps
                  sudo docker build -t ops-ap .
                  echo "Building the Application using Docker"



- stage: DeploymentRelease
  displayName: 'Deployment Release CD'
  dependsOn: Build
  jobs:
      - deployment: Deployment
        displayName: 'Deployment Job'
        pool:
          name: Ops-Pipeline
        environment: 'Deployement'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Docker..."
                    # docker restart apache-cont
                    sudo docker run -d -p 80:80 --name apache-cont ops-ap 
                    
                    echo "Runing  Docker..."
                    sudo docker ps
                    echo "Access the website using http://35.154.73.9/"
