trigger:
- master


stages:
- stage: Build
  displayName: 'Build stage CI'
  jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          name: Ops-Pipeline
        steps:
           - task: CmdLine@2
             displayName: 'Builds'
             inputs:
              script: |
                  sudo cp -R /home/ubuntu/myagent/_work/2/s/* /var/www/practice
                  cd /var/www/practice
                  sudo docker build -t ops-apache .
                  echo "Building the Application using Docker"



- stage: DEVRelease
  displayName: 'DEV Release CD'
  dependsOn: Build
  jobs:
      - deployment: DEVDeployment
        displayName: 'DEV Deployment Job'
        pool:
          name: Ops-Pipeline
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to Docker..."
                    sudo docker run -d -p 80:80 ops-apache
                    echo "Runing  Docker..."
                    sudo docker ps
                    echo "Access the website using http://35.154.73.9/"
