
trigger:
- master


stages:
- stage: Build
  displayName: 'Build stage CI'
  jobs:
      - job: BuildJob
        displayName: 'Build Job'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
           - task: CmdLine@2
             displayName: 'Delay for 10 seconds'
             inputs:
              script: 'sleep 10'
      - job: EchoVariables
        displayName: 'Echo Variables'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: CmdLine@2
            displayName: 'Set Environment Variables'
            inputs:
              script: |
              echo "##vso[task.setvariable variable=DBusername;isOutput=true]$(DBusername)"
              echo "##vso[task.setvariable variable=password;isOutput=true]$(password)"

          - task: CmdLine@2
            displayName: 'Echo Variables'
            inputs:
              script: |
              echo "DBusername: $(DBusername)"
              echo "password:" $(password)"
    
- stage: DEVRelease
  displayName: 'DEV Release CD'
  dependsOn: Build
  jobs:
      - deployment: DEVDeployment
        displayName: 'DEV Deployment Job'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'DEV'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to DEV environment..."

- stage: PREPRODRelease
  displayName: 'PREPROD Release CD'
  dependsOn: DEVRelease
  jobs:
      - deployment: PREPRODDeployment
        displayName: 'PREPROD Deployment Job'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'PREPROD'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to PREPROD environment..."

- stage: PRODRelease
  displayName: 'PROD Release CD'
  dependsOn: PREPRODRelease
  jobs:
      - deployment: PRODDeployment
        displayName: 'PROD Deployment Job'
        pool:
          vmImage: 'ubuntu-latest'
        environment: 'PROD'
        strategy:
          runOnce:
            deploy:
              steps:
                - script: |
                    echo "Deploying to PROD environment..."

  